Enable oauth_version parameter to be "1.0", "1.0a" or not sent
AlexGhiondea/OAuth.net pull request #8
Opened 2018-03-29 09:10 UTC by SimonTouchtech

Fixes #6 
I also added the option to not send "oauth_version" at all. I'm not sure why you wouldn't want to do that (maybe to save a few bytes) but the specification says the parameter is optional, so I thought I might as well add that option.

2018-03-29 17:26 UTC, AlexGhiondea requested changes
Thanks for submitting this! 

I left some comments in the code.

2018-03-29 17:26 UTC, AlexGhiondea commented on src/OAuthMessageHandler.cs
> +            switch (versionParameter)
This code is duplicated. I suggest creating a helper method that takes an `OAuthVersion` enum and returns the string representation for it.

2018-03-29 17:26 UTC, AlexGhiondea commented on src/OAuthVersionParameter.cs
> +    public enum OAuthVersionParameter
Please rename this to `OAuthVersion`.

2018-03-29 17:26 UTC, AlexGhiondea commented on src/OAuthVersionParameter.cs
> +﻿using System;
Sort and Remove usings.

2018-03-29 17:26 UTC, AlexGhiondea commented on src/OAuthMessageHandler.cs
> +                case OAuthVersionParameter.Omit:
You don't needs this case as it is the same as the default case.

2018-03-29 17:26 UTC, AlexGhiondea commented on src/OAuthAuthenticator.cs
> +            switch (versionParameter)
See comment below -- let's put this in a method in the https://github.com/AlexGhiondea/OAuth.net/blob/master/src/Helpers/OAuthHelpers.cs file

2018-03-31 21:17 UTC, AlexGhiondea commented
Closing this as I already merged this.

2018-03-31 21:17 UTC, closed without merging

2018-04-03 06:51 UTC, SimonTouchtech commented
Thanks for the comments, I'm sorry I wasn't able to fix this due to being away during Easter. Looks like you have been doing a bunch of stuff while I was gone though, good work!